### ISSUE TITLE
md语法任务列表渲染问题

### ISSUE THREAD

**Issue by jiewenhuang** [DioxideCN/Tool-Bench#10]
<img width="552" alt="image" src="https://github.com/DioxideCN/Tool-Bench/assets/68629578/36e7a090-f269-433c-9fa0-dcffe6728eb3">  

正常情况
<img width="693" alt="image" src="https://github.com/DioxideCN/Tool-Bench/assets/68629578/e1a89aeb-f282-42ff-a7c9-fc76c518878f">  

用插件后
<img width="319" alt="image" src="https://github.com/DioxideCN/Tool-Bench/assets/68629578/a66ee02b-a343-40ac-a4b3-ff8574d9766c">  

编辑器：ByteMD

**Comment by MoritzArena** [comment]
已在1.0.4-ea-4中得到修复
https://github.com/DioxideCN/Tool-Bench/releases/tag/v1.0.4-ea
