### ISSUE TITLE
【建议】代码高亮设置

### ISSUE THREAD

**Issue by wxyShine** [DioxideCN/Tool-Bench#11]
代码高亮是否可以增加启用开关， 如果主题自带代码高亮配置时就和这个冲突了!
![image](https://github.com/DioxideCN/Tool-Bench/assets/42802152/b4563988-3d8a-42ac-a800-e9643b91188a)

**Comment by MoritzArena** [comment]
因为会和目前已有的Prism插件冲突，所以移除该功能
