### ISSUE TITLE
我一开启这个插件就直接500 服务器内部错误了

### ISSUE THREAD

**Issue by nocodeworldbug** [DioxideCN/Tool-Bench#24]
我一开启这个插件就直接 报下面这个错，是我要设置什么东西吗?
![image](https://github.com/DioxideCN/Tool-Bench/assets/12121402/b7489521-e57d-4318-9ac7-24b49f215950)

**Comment by MoritzArena** [comment]
提供一下版本

**Comment by nocodeworldbug** [comment]
**ToolBench 1.0.4
Halo 2.11.3**
![image](https://github.com/DioxideCN/Tool-Bench/assets/12121402/89860d96-57f2-425a-8803-e3a4ef583e47)
**我安装以后直接就打开，什么都没有设置的，打开就错误，关闭就好了**

**Comment by MoritzArena** [comment]
halo 2.11还没有做适配

**Comment by nocodeworldbug** [comment]
请问现在最高支持到什么版本

**Comment by MoritzArena** [comment]
Halo 2.10.x版本还是支持的

**Comment by nocodeworldbug** [comment]
好的，谢谢您的解答
