### ISSUE TITLE
用了这个插件后，公式无法正常渲染

### ISSUE THREAD

**Issue by sqwfly** [DioxideCN/Tool-Bench#4]
用了这个插件后，公式无法正常渲染

**Comment by MoritzArena** [comment]
是加了katex插件，还是主题自带了Latex的渲染

**Comment by sqwfly** [comment]
加了katex插件，只加katex插件可以渲染公式，再加上Tool-Bench插件公式渲染就失效了

**Comment by MoritzArena** [comment]
这个问题不好解决，两个插件实现的`ReactivePostContentHandler`接口都对文章内容进行了新的渲染导致了冲突。

**Comment by sqwfly** [comment]
> 这个问题不好解决，两个插件实现的`ReactivePostContentHandler`接口都对文章内容进行了新的渲染导致了冲突。

好吧
