### ISSUE TITLE
非常实用的插件，但希望能集成到官方编辑器里

### ISSUE THREAD

**Issue by ZHEYESHIYU** [DioxideCN/Tool-Bench#7]
前两天还在官方issue下面提相关问题，官方他们也有类似推进的想法，不知道大佬能不能跟他们商议一下？[4600](https://github.com/halo-dev/halo/issues/4600)
我看插件里还内置了插入自定义的 HTML 代码的选项，那这样是不是可以后续开发一个模板库，让用户能自定义和上传发布？
因为我是纯小白使用者，难以在开发层帮上忙，所以就提一点可能有意思的建议啦~

**Comment by ZHEYESHIYU** [comment]
官方那边设计了一个扩展[编辑器 block [的示例插件](https://github.com/halo-dev/halo/issues/4600#issuecomment-1722791004)，大佬可以去看看]

**Comment by MoritzArena** [comment]
后面可能会考虑，但目前已经在开发新的markdown编辑器了暂时不太会考虑
