### ISSUE TITLE
作者大佬，请问新的编辑器有没有加入快捷图标的方法，方便使用joe等主题的特色样式

### ISSUE THREAD

**Issue by Dion-Lee** [DioxideCN/Tool-Bench#8]
类似于这样的
<img width="938" alt="image" src="https://github.com/DioxideCN/Tool-Bench/assets/68332968/b0d9f524-0651-4442-b270-e0a043bf1c64">

**Comment by MoritzArena** [comment]
我正在开发这方面相关的功能，来尝试自动适配主题中的自定义元素。相关内容已在 #3 中提出。

**Comment by Dion-Lee** [comment]
> 我正在开发这方面相关的功能，来尝试自动适配主题中的自定义元素。相关内容已在 #3 中提出。

支持，Halo就是缺这样的编辑器插件，适当付费都可以👍
